<a href="https://colab.research.google.com/github/GYAN2020/Authentication/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy - Numerical Arrays:**

In [ ]:
import numpy as np

In [ ]:
from time import process_time

In [ ]:
python_list = [i for i in range(1000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time-start_time)

0.00029952899999985405


In [ ]:
print(python_list)

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224,

In [ ]:
np_array = np.array([i for i in range(1000)])
start_time = process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.00016238700000048567


Numpy Arrays


In [ ]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

.ndarray mean n dimension array

In [ ]:
#creating a 1 dim array
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape


(4,)

In [ ]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype= float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholder in numpy

In [ ]:
#create a numpy array of Zeros
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create a numpy array of ones
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#create a numpy array of a particular value
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#create an identity matrix
a= np.eye(5)
print(a)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#create a numpy array with random values
b=np.random.random((3,4))
print(b)

[[0.60310665 0.64892087 0.05798361 0.7416464 ]
 [0.61756553 0.03795387 0.53309739 0.88870689]
 [0.54680214 0.06133216 0.09944485 0.84325447]]


In [ ]:
#random integer values array within a specific range
c=np.random.randint(10,100,(3,5))
print(c)

[[96 92 96 65 26]
 [32 96 23 19 77]
 [59 61 47 47 38]]


In [ ]:
print(c.shape)

(3, 5)


In [ ]:
# array of evenly spaced values --> specifying the number of values required
d=np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [29]:
#array of evenly spaced values --> specifying the step
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


In [31]:
#convert a list to numpy array
list2=[10,20,30,40,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

**Analysing a numpy array**

In [33]:
c=np.random.randint(10,90,(5,5))
print(c)

[[13 46 24 52 85]
 [19 41 12 38 60]
 [74 32 48 37 83]
 [85 77 42 51 73]
 [85 59 74 18 72]]


In [34]:
#print array dimensions
print(c.shape)

(5, 5)


In [35]:
#number of dimension
print(c.ndim)

2


In [36]:
#cheching the data type of the values in the array
print(c.dtype)

int64


In [37]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [5]:
import numpy as np
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))


In [6]:
print(a)
print(b)

[[8 1 5]
 [1 5 0]
 [7 9 9]]
[[10 10 12]
 [14 19 18]
 [14 17 18]]


In [7]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[18 11 17]
 [15 24 18]
 [21 26 27]]
[[ -2  -9  -7]
 [-13 -14 -18]
 [ -7  -8  -9]]
[[ 80  10  60]
 [ 14  95   0]
 [ 98 153 162]]
[[0.8        0.1        0.41666667]
 [0.07142857 0.26315789 0.        ]
 [0.5        0.52941176 0.5       ]]


In [10]:
a= np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))

In [9]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[26 16 18]
 [11 17 28]
 [19 17 21]]
[[-12  -8 -14]
 [-11 -13 -10]
 [-19  -5 -13]]
[[133  48  32]
 [  0  30 171]
 [  0  66  68]]
[[0.36842105 0.33333333 0.125     ]
 [0.         0.13333333 0.47368421]
 [0.         0.54545455 0.23529412]]


Array Manipulation

In [12]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 1 2]
 [4 4 8]]
(2, 3)


In [13]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[4 4]
 [1 4]
 [2 8]]
(3, 2)


In [14]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 0 9]
 [1 9 4]]
(2, 3)


In [15]:
trans2=array.T
print(trans2)
print(trans.shape)

[[6 1]
 [0 9]
 [9 4]]
(3, 2)


In [18]:
#reshaping a array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[5 1 7]
 [6 4 2]]
(2, 3)


In [19]:
#reshaping a array
b=a.reshape(3,2)
print(b)
print(b.shape)

[[5 1]
 [7 6]
 [4 2]]
(3, 2)
