<a href="https://colab.research.google.com/github/GYAN2020/Authentication/blob/main/StandardScaler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('/content/auto-mpg.csv')

In [3]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model year  origin                   car name  
0          70       1  chevrolet chevelle malibu  
1          70       1          buick skylark 320  
2          70       1         plymouth satellite  
3          87       1              amc rebel sst  
4          70       1                ford torino

In [5]:
df.tail()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model year  origin         car name  
393          82       1  ford mustang gl  
394          82       2        vw pickup  
395          82       1    dodge rampage  
396          82       1      ford ranger  
397          82       1       chevy s-10

In [6]:
df.shape

(398, 9)

In [7]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model year        int64
origin            int64
car name         object
dtype: object

In [8]:
X=df.iloc[:,[2,4]]
y=df.iloc[:,5]

In [9]:
X.head()

displacement  weight
0         307.0    3504
1         350.0    3693
2         318.0    3436
3         304.0    3433
4         302.0    3449

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=40)

In [12]:
X_train.head()

displacement  weight
256         225.0    3430
295          98.0    1915
100         250.0    3021
253         200.0    3155
369         112.0    2395

In [13]:
scalar=StandardScaler().fit(X_train)

In [14]:
print(scalar)

StandardScaler()


In [15]:
scalar.mean_

array([ 193.29362416, 2978.66107383])

In [17]:
scalar.transform(X_train)

array([[ 3.09515168e-01,  5.45553226e-01],
       [-9.30248927e-01, -1.28569396e+00],
       [ 5.53563218e-01,  5.11769237e-02],
       [ 6.54671179e-02,  2.13148622e-01],
       [-7.93582019e-01, -7.05496830e-01],
       [-6.95962799e-01, -8.08240072e-01],
       [-4.81200515e-01, -3.79135946e-01],
       [-1.19382082e+00, -1.45733561e+00],
       [ 1.21737392e+00,  1.40376148e+00],
       [-8.61915473e-01, -1.00163911e+00],
       [ 3.77848622e-01,  3.73911576e-01],
       [ 7.19515893e-01,  7.57083429e-01],
       [-8.42391629e-01, -6.63190790e-01],
       [ 1.21737392e+00,  1.46419868e+00],
       [ 6.70706282e-01,  4.39244596e-02],
       [-7.64296253e-01, -3.44082370e-01],
       [ 6.54671179e-02, -1.65127412e-02],
       [ 2.30094726e+00,  2.38526162e+00],
       [-9.40010849e-01, -9.55706842e-01],
       [ 1.06118316e+00,  2.30071038e-01],
       [ 1.09046893e+00,  1.08948803e+00],
       [ 3.68086700e-01,  4.85116025e-01],
       [-6.95962799e-01, -9.17027033e-01],
       [-1.

In [18]:
X_train_scaled=scalar.transform(X_train)

print(X_train_scaled)

In [20]:
print(X_train_scaled.mean(axis=0))

[-9.53748639e-17 -2.14593444e-16]


In [21]:
print(X_train_scaled.std(axis=0))

[1. 1.]


In [22]:
scaler=StandardScaler().fit(X_test)

In [23]:
scaler.mean_

array([ 219.92, 2945.88])

In [24]:
scaler.transform(X_test)

array([[-0.47085548, -1.09436579],
       [ 0.01697379,  0.74278987],
       [-0.33052103, -0.48420743],
       [-0.47419678, -1.06987038],
       [-0.34722752, -0.8772474 ],
       [ 0.04036286, -0.03549607],
       [-0.34722752, -0.80821488],
       [-0.43075992, -1.10327321],
       [ 0.54489861,  2.23700981],
       [-0.43075992, -1.28142164],
       [ 0.2809362 ,  0.54237289],
       [-0.21357566, -0.40181378],
       [-0.41071215, -1.10884035],
       [-0.33386233, -0.87502054],
       [ 0.60170064,  2.00430342],
       [-0.2670364 , -0.34168868],
       [ 0.2809362 ,  0.8084821 ],
       [ 0.2742536 ,  0.56018773],
       [ 0.29096009,  1.59233518],
       [-0.41071215, -0.90842337],
       [ 0.2742536 ,  1.88405323],
       [-0.26369511,  0.27180996],
       [-0.29710807, -0.129024  ],
       [ 0.43797712,  1.31731855],
       [-0.41071215, -0.86277284],
       [-0.43075992, -1.06987038],
       [ 0.12723656,  0.87306091],
       [ 9.28907113,  1.00667223],
       [ 0.43463583,

In [25]:
X_test_scaled=scaler.transform(X_testMB)

In [26]:
print(X_test_scaled)

[[-0.47085548 -1.09436579]
 [ 0.01697379  0.74278987]
 [-0.33052103 -0.48420743]
 [-0.47419678 -1.06987038]
 [-0.34722752 -0.8772474 ]
 [ 0.04036286 -0.03549607]
 [-0.34722752 -0.80821488]
 [-0.43075992 -1.10327321]
 [ 0.54489861  2.23700981]
 [-0.43075992 -1.28142164]
 [ 0.2809362   0.54237289]
 [-0.21357566 -0.40181378]
 [-0.41071215 -1.10884035]
 [-0.33386233 -0.87502054]
 [ 0.60170064  2.00430342]
 [-0.2670364  -0.34168868]
 [ 0.2809362   0.8084821 ]
 [ 0.2742536   0.56018773]
 [ 0.29096009  1.59233518]
 [-0.41071215 -0.90842337]
 [ 0.2742536   1.88405323]
 [-0.26369511  0.27180996]
 [-0.29710807 -0.129024  ]
 [ 0.43797712  1.31731855]
 [-0.41071215 -0.86277284]
 [-0.43075992 -1.06987038]
 [ 0.12723656  0.87306091]
 [ 9.28907113  1.00667223]
 [ 0.43463583  1.72928679]
 [-0.37395789 -0.75811063]
 [-0.43744252 -1.08879865]
 [-0.06655862  0.13819864]
 [-0.40737085 -0.76924491]
 [-0.33720363 -0.60223076]
 [ 0.43463583  1.66359456]
 [-0.16345622  0.04244386]
 [-0.23028214 -0.3461424 ]
 

In [30]:
print(X_test_scaled.mean(axis=0))

[ 3.09821613e-17 -1.09912079e-16]


In [31]:
print(X_test_scaled.std(axis=0))

[1. 1.]
